In [1]:
import pandas as pd
data=pd.read_csv('enhanced_zomato_dataset_clean.csv')

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 123657 entries, 0 to 123656
Data columns (total 26 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Restaurant_Name        123657 non-null  object
 1   Dining_Rating          123657 non-null  float64
 2   Delivery_Rating        123657 non-null  float64
 3   Dining_Votes           123657 non-null  int64
 4   Delivery_Votes         123657 non-null  int64
 5   Cuisine                123657 non-null  object
 6   Place_Name             123657 non-null  object
 7   City                   123657 non-null  object
 8   Item_Name              123657 non-null  object
 9   Best_Seller            123657 non-null  object
 10  Votes                  123657 non-null  int64
 11  Prices                 123657 non-null  float64
 12  Average_Rating         123657 non-null  float64
 13  Total_Votes            123657 non-null  int64
 14  Price_per_Vote         123657 non-null  float64
 15  Log_Price              123657 non-null  float64
 16  Is_Bestseller          123657 non-null  int64
 17  Restaurant_Popularity  123657 non-null  int64
 18  Avg_Rating_Restaurant  123657 non-null  float64
 19  Avg_Price_Restaurant   123657 non-null  float64
 20  Avg_Rating_Cuisine     123657 non-null  float64
 21  Avg_Price_Cuisine      123657 non-null  float64
 22  Avg_Rating_City        123657 non-null  float64
 23  Avg_Price_City         123657 non-null  float64
 24  Is_Highly_Rated        123657 non-null  int64
 25  Is_Expensive           123657 non-null  int64
dtypes: float64(12), int64(8), object(6)
memory usage: 24.5+ MB

In [3]:
# check for duplicate records where Restraunt name and Item_Name are same and only show their index and the records
data[data.duplicated(subset=['Restaurant_Name', 'Item_Name'], keep=False)].sort_values(by=['Restaurant_Name', 'Item_Name'])

,Restaurant_Name,Dining_Rating,Delivery_Rating,Dining_Votes,Delivery_Votes,Cuisine,Place_Name,City,Item_Name,Best_Seller,...,Is_Bestseller,Restaurant_Popularity,Avg_Rating_Restaurant,Avg_Price_Restaurant,Avg_Rating_Cuisine,Avg_Price_Cuisine,Avg_Rating_City,Avg_Price_City,Is_Highly_Rated,Is_Expensive
60171,12 To 12 BBQ,4.000000,4.0,104,0,Biryani,Panampilly Nagar,Kochi,12 to 12 Fried Chicken with Garlic Rice,NONE,...,1,162,4.000000,273.364198,3.875916,266.881510,3.869203,225.954220,1,1
60183,12 To 12 BBQ,4.000000,4.0,104,0,Biryani,Panampilly Nagar,Kochi,12 to 12 Fried Chicken with Garlic Rice,NONE,...,1,162,4.000000,273.364198,3.875916,266.881510,3.869203,225.954220,1,1
60172,12 To 12 BBQ,4.000000,4.0,104,0,Biryani,Panampilly Nagar,Kochi,Alfaham Lebanese,NONE,...,1,162,4.000000,273.364198,3.875916,266.881510,3.869203,225.954220,1,1
60178,12 To 12 BBQ,4.000000,4.0,104,0,Biryani,Panampilly Nagar,Kochi,Alfaham Lebanese,NONE,...,1,162,4.000000,273.364198,3.875916,266.881510,3.869203,225.954220,1,1
60157,12 To 12 BBQ,4.000000,4.0,104,0,Biryani,Panampilly Nagar,Kochi,Arabian Chicken Biryani,MUST TRY,...,1,162,4.000000,273.364198,3.875916,266.881510,3.869203,225.954220,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6323,Zomoz - The Momo Company,3.822264,4.3,0,726,Fast Food,Abids,Hyderabad,Veg Manchurian Steamed Momos (6pcs),CHEF'S SPECIAL,...,1,91,4.061132,158.806703,3.818680,255.954894,3.939031,245.130482,1,0
6279,Zomoz - The Momo Company,3.822264,4.3,0,726,Fast Food,Abids,Hyderabad,Veg Steamed Momos (6pcs),MUST TRY,...,1,91,4.061132,158.806703,3.818680,255.954894,3.939031,245.130482,1,0
6321,Zomoz - The Momo Company,3.822264,4.3,0,726,Fast Food,Abids,Hyderabad,Veg Steamed Momos (6pcs),CHEF'S SPECIAL,...,1,91,4.061132,158.806703,3.818680,255.954894,3.939031,245.130482,1,0
6290,Zomoz - The Momo Company,3.822264,4.3,0,726,Fast Food,Abids,Hyderabad,Zesty Chicken Steamed Momos (6pcs),MUST TRY,...,1,91,4.061132,158.806703,3.818680,255.954894,3.939031,245.130482,1,0
6326,Zomoz - The Momo Company,3.822264,4.3,0,726,Fast Food,Abids,Hyderabad,Zesty Chicken Steamed Momos (6pcs),CHEF'S SPECIAL,...,1,91,4.061132,158.806703,3.818680,255.954894,3.939031,245.130482,1,0

In [4]:
# keep only the first occurence of the duplicate records and drop the rest
data.drop_duplicates(subset=['Restaurant_Name', 'Item_Name'], keep='first', inplace=True)
data

,Restaurant_Name,Dining_Rating,Delivery_Rating,Dining_Votes,Delivery_Votes,Cuisine,Place_Name,City,Item_Name,Best_Seller,...,Is_Bestseller,Restaurant_Popularity,Avg_Rating_Restaurant,Avg_Price_Restaurant,Avg_Rating_Cuisine,Avg_Price_Cuisine,Avg_Rating_City,Avg_Price_City,Is_Highly_Rated,Is_Expensive
0,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Platter Kebab Combo,BESTSELLER,...,1,46,4.05,171.347826,3.818680,255.954894,3.939031,245.130482,1,0
1,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Rumali Shawarma,BESTSELLER,...,1,46,4.05,171.347826,3.818680,255.954894,3.939031,245.130482,1,0
2,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken Tandoori Salad,NONE,...,1,46,4.05,171.347826,3.818680,255.954894,3.939031,245.130482,1,0
3,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Chicken BBQ Salad,BESTSELLER,...,1,46,4.05,171.347826,3.818680,255.954894,3.939031,245.130482,1,0
4,Doner King,3.9,4.2,39,0,Fast Food,Malakpet,Hyderabad,Special Doner Wrap Combo,MUST TRY,...,1,46,4.05,171.347826,3.818680,255.954894,3.939031,245.130482,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123630,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Pineapple Raita,NONE,...,1,286,4.05,354.475524,3.885698,208.939511,3.880503,194.591645,1,0
123631,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Fruit Raita,NONE,...,1,286,4.05,354.475524,3.885698,208.939511,3.880503,194.591645,1,0
123632,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Boondi Raita,NONE,...,1,286,4.05,354.475524,3.885698,208.939511,3.880503,194.591645,1,0
123633,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Mint Raita,NONE,...,1,286,4.05,354.475524,3.885698,208.939511,3.880503,194.591645,1,0
123634,Ariena Boutique Hotel,3.9,4.2,13,523,Pizza,Purena,Raipur,Mint Chutney,NONE,...,1,286,4.05,354.475524,3.885698,208.939511,3.880503,194.591645,1,0

In [5]:
# check for duplicate records where Restraunt name and Item_Name are same and only show their index and the records
data[data.duplicated(subset=['Restaurant_Name', 'Item_Name'], keep=False)].sort_values(by=['Restaurant_Name', 'Item_Name'])

Empty DataFrame
Columns: [Restaurant_Name, Dining_Rating, Delivery_Rating, Dining_Votes, Delivery_Votes, Cuisine, Place_Name, City, Item_Name, Best_Seller, Votes, Prices, Average_Rating, Total_Votes, Price_per_Vote, Log_Price, Is_Bestseller, Restaurant_Popularity, Avg_Rating_Restaurant, Avg_Price_Restaurant, Avg_Rating_Cuisine, Avg_Price_Cuisine, Avg_Rating_City, Avg_Price_City, Is_Highly_Rated, Is_Expensive]
Index: []

[0 rows x 26 columns]

In [7]:
from sqlalchemy import create_engine
# Database connection parameters
DB_USER = "root"
DB_PASSWORD = "nitya"
DB_HOST = "localhost"       # or IP address
DB_PORT = 3306              # default MySQL port
DB_NAME = "zepto"


engine = create_engine(
        f"mysql+pymysql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}",
        echo=True,           # Set to True to log SQL queries
        pool_pre_ping=True,  # Helps avoid stale connections
        pool_recycle=3600    # Recycle connections every hour
    )

In [8]:
# send data to mysql database
data.to_sql(name='Zepto_Data', con=engine, if_exists='append', index=False)

2026-07-15 21:02:00,096 INFO sqlalchemy.engine.Engine SELECT DATABASE()
2026-07-15 21:02:00,096 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-07-15 21:02:00,107 INFO sqlalchemy.engine.Engine SELECT @@sql_mode
2026-07-15 21:02:00,107 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-07-15 21:02:00,107 INFO sqlalchemy.engine.Engine SELECT @@lower_case_table_names
2026-07-15 21:02:00,107 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-07-15 21:02:00,107 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-07-15 21:02:00,198 INFO sqlalchemy.engine.Engine DESCRIBE `zepto`.`Zepto_Data`
2026-07-15 21:02:00,198 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-07-15 21:02:00,204 INFO sqlalchemy.engine.Engine
CREATE TABLE `Zepto_Data` (
	`Restaurant_Name` TEXT,
	`Dining_Rating` FLOAT(53),
	`Delivery_Rating` FLOAT(53),
	`Dining_Votes` BIGINT,
	`Delivery_Votes` BIGINT,
	`Cuisine` TEXT,
	`Place_Name` TEXT,
	`City` TEXT,
	`Item_Name` TEXT,
	`Best_Seller` TEXT,
	`Votes` BIGINT,
	`Prices` FLOAT(53),
	`Average_Rating` FLOAT(53),
	`Total_Votes` BIGINT,
	`Price_per_Vote` FLOAT(53),
	`Log_Price` FLOAT(53),
	`Is_Bestseller` BIGINT,
	`Restaurant_Popularity` BIGINT,
	`Avg_Rating_Restaurant` FLOAT(53),
	`Avg_Price_Restaurant` FLOAT(53),
	`Avg_Rating_Cuisine` FLOAT(53),
	`Avg_Price_Cuisine` FLOAT(53),
	`Avg_Rating_City` FLOAT(53),
	`Avg_Price_City` FLOAT(53),
	`Is_Highly_Rated` BIGINT,
	`Is_Expensive` BIGINT
)


2026-07-15 21:02:00,204 INFO sqlalchemy.engine.Engine [no key 0.00143s] {}
2026-07-15 21:02:02,091 INFO sqlalchemy.engine.Engine INSERT INTO `Zepto_Data` (`Restaurant_Name`, `Dining_Rating`, `Delivery_Rating`, `Dining_Votes`, `Delivery_Votes`, `Cuisine`, `Place_Name`, `City`, `Item_Name`, `Best_Seller`, `Votes`, `Prices`, `Average_Rating`, `Total_Votes`, `Price_per_Vote`, `Log_Price`, `Is_Bestseller`, `Restaurant_Popularity`, `Avg_Rating_Restaurant`, `Avg_Price_Restaurant`, `Avg_Rating_Cuisine`, `Avg_Price_Cuisine`, `Avg_Rating_City`, `Avg_Price_City`, `Is_Highly_Rated`, `Is_Expensive`) VALUES (%(Restaurant_Name)s, %(Dining_Rating)s, %(Delivery_Rating)s, %(Dining_Votes)s, %(Delivery_Votes)s, %(Cuisine)s, %(Place_Name)s, %(City)s, %(Item_Name)s, %(Best_Seller)s, %(Votes)s, %(Prices)s, %(Average_Rating)s, %(Total_Votes)s, %(Price_per_Vote)s, %(Log_Price)s, %(Is_Bestseller)s, %(Restaurant_Popularity)s, %(Avg_Rating_Restaurant)s, %(Avg_Price_Restaurant)s, %(Avg_Rating_Cuisine)s, %(Avg_Price_Cuisine)s, %(Avg_Rating_City)s, %(Avg_Price_City)s, %(Is_Highly_Rated)s, %(Is_Expensive)s)
2026-07-15 21:02:02,091 INFO sqlalchemy.engine.Engine [generated in 1.24680s] [{'Restaurant_Name': 'Doner King', 'Dining_Rating': 3.9, 'Delivery_Rating': 4.2, 'Dining_Votes': 39, 'Delivery_Votes': 0, 'Cuisine': 'Fast Food', 'Place_Name': 'Malakpet', 'City': ' Hyderabad', 'Item_Name': 'Platter Kebab Combo', 'Best_Seller': 'BESTSELLER', 'Votes': 84, 'Prices': 249.0, 'Average_Rating': 4.05, 'Total_Votes': 39, 'Price_per_Vote': 2.929411764705882, 'Log_Price': 5.521460917862246, 'Is_Bestseller': 1, 'Restaurant_Popularity': 46, 'Avg_Rating_Restaurant': 4.05, 'Avg_Price_Restaurant': 171.34782608695653, 'Avg_Rating_Cuisine': 3.8186797045130767, 'Avg_Price_Cuisine': 255.9548939215356, 'Avg_Rating_City': 3.9390311407230185, 'Avg_Price_City': 245.13048229039904, 'Is_Highly_Rated': 1, 'Is_Expensive': 0}, {'Restaurant_Name': 'Doner King', 'Dining_Rating': 3.9, 'Delivery_Rating': 4.2, 'Dining_Votes': 39, 'Delivery_Votes': 0, 'Cuisine': 'Fast Food', 'Place_Name': 'Malakpet', 'City': ' Hyderabad', 'Item_Name': 'Chicken Rumali Shawarma', 'Best_Seller': 'BESTSELLER', 'Votes': 45, 'Prices': 129.0, 'Average_Rating': 4.05, 'Total_Votes': 39, 'Price_per_Vote': 2.8043478260869565, 'Log_Price': 4.867534450455582, 'Is_Bestseller': 1, 'Restaurant_Popularity': 46, 'Avg_Rating_Restaurant': 4.05, 'Avg_Price_Restaurant': 171.34782608695653, 'Avg_Rating_Cuisine': 3.8186797045130767, 'Avg_Price_Cuisine': 255.9548939215356, 'Avg_Rating_City': 3.9390311407230185, 'Avg_Price_City': 245.13048229039904, 'Is_Highly_Rated': 1, 'Is_Expensive': 0}, {'Restaurant_Name': 'Doner King', 'Dining_Rating': 3.9, 'Delivery_Rating': 4.2, 'Dining_Votes': 39, 'Delivery_Votes': 0, 'Cuisine': 'Fast Food', 'Place_Name': 'Malakpet', 'City': ' Hyderabad', 'Item_Name': 'Chicken Tandoori Salad', 'Best_Seller': 'NONE', 'Votes': 39, 'Prices': 189.0, 'Average_Rating': 4.05, 'Total_Votes': 39, 'Price_per_Vote': 4.725, 'Log_Price': 5.247024072160486, 'Is_Bestseller': 1, 'Restaurant_Popularity': 46, 'Avg_Rating_Restaurant': 4.05, 'Avg_Price_Restaurant': 171.34782608695653, 'Avg_Rating_Cuisine': 3.8186797045130767, 'Avg_Price_Cuisine': 255.9548939215356, 'Avg_Rating_City': 3.9390311407230185, 'Avg_Price_City': 245.13048229039904, 'Is_Highly_Rated': 1, 'Is_Expensive': 0}, {'Restaurant_Name': 'Doner King', 'Dining_Rating': 3.9, 'Delivery_Rating': 4.2, 'Dining_Votes': 39, 'Delivery_Votes': 0, 'Cuisine': 'Fast Food', 'Place_Name': 'Malakpet', 'City': ' Hyderabad', 'Item_Name': 'Chicken BBQ Salad', 'Best_Seller': 'BESTSELLER', 'Votes': 43, 'Prices': 189.0, 'Average_Rating': 4.05, 'Total_Votes': 39, 'Price_per_Vote': 4.295454545454546, 'Log_Price': 5.247024072160486, 'Is_Bestseller': 1, 'Restaurant_Popularity': 46, 'Avg_Rating_Restaurant': 4.05, 'Avg_Price_Restaurant': 171.34782608695653, 'Avg_Rating_Cuisine': 3.8186797045130767, 'Avg_Price_Cuisine': 255.9548939215356, 'Avg_Rating_City': 3.9390311407230185, 'Avg_Price_City': 245.13048229039904, 'Is_Highly_Rated': 1, 'Is_Expensive': 0}, {'Restaurant_Name': 'Doner King', 'Dining_Rating': 3.9, 'Delivery_Rating': 4.2, 'Dining_Votes': 39, 'Delivery_Votes': 0, 'Cuisine': 'Fast Food', 'Place_Name': 'Malakpet', 'City': ' Hyderabad', 'Item_Name': 'Special Doner Wrap Combo', 'Best_Seller': 'MUST TRY', 'Votes': 31, 'Prices': 205.0, 'Average_Rating': 4.05, 'Total_Votes': 39, 'Price_per_Vote': 6.40625, 'Log_Price': 5.327876168789581, 'Is_Bestseller': 1, 'Restaurant_Popularity': 46, 'Avg_Rating_Restaurant': 4.05, 'Avg_Price_Restaurant': 171.34782608695653, 'Avg_Rating_Cuisine': 3.8186797045130767, 'Avg_Price_Cuisine': 255.9548939215356, 'Avg_Rating_City': 3.9390311407230185, 'Avg_Price_City': 245.13048229039904, 'Is_Highly_Rated': 1, 'Is_Expensive': 0}, {'Restaurant_Name': 'Doner King', 'Dining_Rating': 3.9, 'Delivery_Rating': 4.2, 'Dining_Votes': 39, 'Delivery_Votes': 0, 'Cuisine': 'Fast Food', 'Place_Name': 'Malakpet', 'City': ' Hyderabad', 'Item_Name': 'Chicken Tandoori Pizza [8 inches]', 'Best_Seller': 'BESTSELLER', 'Votes': 48, 'Prices': 199.0, 'Average_Rating': 4.05, 'Total_Votes': 39, 'Price_per_Vote': 4.061224489795919, 'Log_Price': 5.298317366548036, 'Is_Bestseller': 1, 'Restaurant_Popularity': 46, 'Avg_Rating_Restaurant': 4.05, 'Avg_Price_Restaurant': 171.34782608695653, 'Avg_Rating_Cuisine': 3.8186797045130767, 'Avg_Price_Cuisine': 255.9548939215356, 'Avg_Rating_City': 3.9390311407230185, 'Avg_Price_City': 245.13048229039904, 'Is_Highly_Rated': 1, 'Is_Expensive': 0}, {'Restaurant_Name': 'Doner King', 'Dining_Rating': 3.9, 'Delivery_Rating': 4.2, 'Dining_Votes': 39, 'Delivery_Votes': 0, 'Cuisine': 'Fast Food', 'Place_Name': 'Malakpet', 'City': ' Hyderabad', 'Item_Name': 'Special Zinger Tortilla Wrap', 'Best_Seller': "CHEF'S SPECIAL", 'Votes': 27, 'Prices': 165.0, 'Average_Rating': 4.05, 'Total_Votes': 39, 'Price_per_Vote': 5.892857142857143, 'Log_Price': 5.111987788356544, 'Is_Bestseller': 1, 'Restaurant_Popularity': 46, 'Avg_Rating_Restaurant': 4.05, 'Avg_Price_Restaurant': 171.34782608695653, 'Avg_Rating_Cuisine': 3.8186797045130767, 'Avg_Price_Cuisine': 255.9548939215356, 'Avg_Rating_City': 3.9390311407230185, 'Avg_Price_City': 245.13048229039904, 'Is_Highly_Rated': 1, 'Is_Expensive': 0}, {'Restaurant_Name': 'Doner King', 'Dining_Rating': 3.9, 'Delivery_Rating': 4.2, 'Dining_Votes': 39, 'Delivery_Votes': 0, 'Cuisine': 'Fast Food', 'Place_Name': 'Malakpet', 'City': ' Hyderabad', 'Item_Name': 'Chicken Popcorn [20 Pieces]', 'Best_Seller': 'BESTSELLER', 'Votes': 59, 'Prices': 165.0, 'Average_Rating': 4.05, 'Total_Votes': 39, 'Price_per_Vote': 2.75, 'Log_Price': 5.111987788356544, 'Is_Bestseller': 1, 'Restaurant_Popularity': 46, 'Avg_Rating_Restaurant': 4.05, 'Avg_Price_Restaurant': 171.34782608695653, 'Avg_Rating_Cuisine': 3.8186797045130767, 'Avg_Price_Cuisine': 255.9548939215356, 'Avg_Rating_City': 3.9390311407230185, 'Avg_Price_City': 245.13048229039904, 'Is_Highly_Rated': 1, 'Is_Expensive': 0}  ... displaying 10 of 88428 total bound parameter sets ...  {'Restaurant_Name': 'Ariena Boutique Hotel', 'Dining_Rating': 3.9, 'Delivery_Rating': 4.2, 'Dining_Votes': 13, 'Delivery_Votes': 523, 'Cuisine': 'Pizza', 'Place_Name': 'Purena', 'City': ' Raipur', 'Item_Name': 'Mint Raita', 'Best_Seller': 'NONE', 'Votes': 0, 'Prices': 125.0, 'Average_Rating': 4.05, 'Total_Votes': 536, 'Price_per_Vote': 125.0, 'Log_Price': 4.836281906951478, 'Is_Bestseller': 1, 'Restaurant_Popularity': 286, 'Avg_Rating_Restaurant': 4.05, 'Avg_Price_Restaurant': 354.4755244755245, 'Avg_Rating_Cuisine': 3.885698266216109, 'Avg_Price_Cuisine': 208.93951076841265, 'Avg_Rating_City': 3.88050276140589, 'Avg_Price_City': 194.59164545454544, 'Is_Highly_Rated': 1, 'Is_Expensive': 0}, {'Restaurant_Name': 'Ariena Boutique Hotel', 'Dining_Rating': 3.9, 'Delivery_Rating': 4.2, 'Dining_Votes': 13, 'Delivery_Votes': 523, 'Cuisine': 'Pizza', 'Place_Name': 'Purena', 'City': ' Raipur', 'Item_Name': 'Mint Chutney', 'Best_Seller': 'NONE', 'Votes': 0, 'Prices': 50.0, 'Average_Rating': 4.05, 'Total_Votes': 536, 'Price_per_Vote': 50.0, 'Log_Price': 3.9318256327243257, 'Is_Bestseller': 1, 'Restaurant_Popularity': 286, 'Avg_Rating_Restaurant': 4.05, 'Avg_Price_Restaurant': 354.4755244755245, 'Avg_Rating_Cuisine': 3.885698266216109, 'Avg_Price_Cuisine': 208.93951076841265, 'Avg_Rating_City': 3.88050276140589, 'Avg_Price_City': 194.59164545454544, 'Is_Highly_Rated': 1, 'Is_Expensive': 0}]
2026-07-15 21:02:08,571 INFO sqlalchemy.engine.Engine SHOW FULL TABLES FROM `zepto`
2026-07-15 21:02:08,571 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-07-15 21:02:08,571 INFO sqlalchemy.engine.Engine COMMIT

C:\Users\nitya\AppData\Local\Temp\ipykernel_2492\3357080244.py:2: UserWarning: The provided table name 'Zepto_Data' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  data.to_sql(name='Zepto_Data', con=engine, if_exists='append', index=False)

88428

In [9]:
Unique_cuisines = pd.read_sql("SELECT DISTINCT cuisine FROM Zepto_Data", con=engine)

2026-07-15 21:10:55,787 INFO sqlalchemy.engine.Engine BEGIN (implicit)
2026-07-15 21:10:55,792 INFO sqlalchemy.engine.Engine DESCRIBE `zepto`.`SELECT DISTINCT cuisine FROM Zepto_Data`
2026-07-15 21:10:55,792 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-07-15 21:10:55,801 INFO sqlalchemy.engine.Engine SELECT DISTINCT cuisine FROM Zepto_Data
2026-07-15 21:10:55,803 INFO sqlalchemy.engine.Engine [raw sql] {}
2026-07-15 21:10:56,151 INFO sqlalchemy.engine.Engine ROLLBACK

In [10]:
Unique_cuisines

          cuisine
0       Fast Food
1           Wraps
2         Biryani
3         Chinese
4       Beverages
5        Desserts
6           Shake
7           Mandi
8    South Indian
9           Kebab
10          Pizza
11         Bakery
12      Ice Cream
13        Mughlai
14   North Indian
15          Momos
16       Shawarma
17         Burger
18        Turkish
19          Rolls
20         Coffee
21        Seafood
22     Hyderabadi
23          Salad
24        Sichuan
25       Sandwich
26        Italian
27       Lucknowi
28    Continental
29       American
30        Mexican
31         Kerala
32            Bbq
33     Rajasthani
34   Healthy Food
35        Tibetan
36    Street Food
37         Mithai
38         Juices
39  Maharashtrian
40           Thai
41     Vietnamese
42          Pasta
43       Gujarati
44    Kathiyawadi
45         Andhra
46         Awadhi
47            Tea